### ISSUE TITLE
Client components need to be imported from folder instead of "ui"

### ISSUE THREAD

**Issue by bernardstein** [dan5py/turborepo-shadcn-ui#10] opened 2023-08-13 07:01 UTC
when trying to use the toaster it needs me to import from components/ui and gives an error if importing from ui

**Comment by dan5py** [comment] 2023-08-13 18:26
Hi @bernardstein, thanks for pointing this out. I'm actually aware of this problem and this is caused by the `index.tsx` in the ui package that's considered a Server Component by default.

**Comment by bernardstein** [comment] 2023-08-13 19:03
thanks for the quick response! I am also trying to get the "customize" feature working from the Themes page on the shadcn site: https://ui.shadcn.com/themes, Its a little more complicated than just the light/dark mode but if your up for the challenge it would be really cool.

**Comment by dan5py** [comment] 2023-08-13 20:36
@bernardstein in the new release ([1.0.3](https://github.com/dan5py/turborepo-shadcn-ui/releases/tag/1.0.3)) you can import using `@ui/components/<component_name>`, I removed the index file since it causes conflicts with start exports.

**Comment by dan5py** [comment] 2023-08-13 20:37
> I am also trying to get the "customize" feature working from the Themes page]

Do you mean you're trying to implement it yourself or just trying to customize the components?

**Comment by bernardstein** [comment] 2023-08-13 21:03
> > I am also trying to get the "customize" feature working from the Themes page]
> 
> Do you mean you're trying to implement it yourself or just trying to customize the components?

I meant I am trying to implement it in my project so a someone on the site can change between themes, border radius, color ... etc.

**Comment by dan5py** [comment] 2023-08-13 21:19
You can use a ThemeSwitcher like shadcn does on its website. You would have the themes defined in your CSS file and then you just  toggle the theme class in the body tag. You can check it [here](https://github.com/shadcn-ui/ui/blob/main/apps/www/components/theme-switcher.tsx).

Hope it helps.

**Comment by gabrielbriks** [comment] 2023-11-01 12:26
@dan5py I am a error of importing, when an page of project web use the prop "use client". This correction of 1.0.3 also correct this ?
![image](https://github.com/dan5py/turborepo-shadcn-ui/assets/37519878/0fa48139-3269-4523-9dbe-8f470b6751ac)

**Comment by martinmorenoc** [comment] 2024-01-04 01:36
> @dan5py I am a error of importing, when an page of project web use the prop "use client". This correction of 1.0.3 also correct this ? ![image](https://private-user-images.githubusercontent.com/37519878/279673111-0fa48139-3269-4523-9dbe-8f470b6751ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzIzOTIsIm5iZiI6MTcwNDMzMjA5MiwicGF0aCI6Ii8zNzUxOTg3OC8yNzk2NzMxMTEtMGZhNDgxMzktMzI2OS00NTIzLTlkYmUtOGY0NzBiNjc1MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAxMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmODZhMzYyOGY3OGY2MTllMTg5ZjI3OWRiOTIyZjY1NzU2YTE3ZTQyYzc0YTA1YTY5MDE5MjJlZmM0NmY4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Thh6uLkjDqSj6N1NZZP57WbOjQjVjP_2q3_RwuiK5UM)

you need change the path of the cn import that comes by default in shadcn component. It should be in `"../../lib/utils"`

**Comment by martinmorenoc** [comment] 2024-01-04 01:38
> @bernardstein in the new release ([1.0.3](https://github.com/dan5py/turborepo-shadcn-ui/releases/tag/1.0.3)) you can import using `@ui/components/<component_name>`, I removed the index file since it causes conflicts with start exports.

any idea of why is this happening? Did you find a solution? I notice that this only happens when you import components from ui in server components

Why the solution wasn't just add `"use client"` on top on `index.tsx` file? It works for me

**Comment by dan5py** [comment] 2024-01-24 14:39
Should be fixed with the latest release `1.1.0`

**Closed as completed by dan5py** 2024-01-24 14:39 UTC
